### ISSUE TITLE
Adding pict for easy GPIO plugging

### ISSUE THREAD

**Issue by Kuronons** [xMasterX/flipper-flashlight#1]
Hey,

I thought it might be nice idea to add a pict on screen showing basic pin GPIO plugging as memo.
Here is a 128x18px png proposal if you want to integrate it on your code.

![Flashlight_pins_128x18](https://user-images.githubusercontent.com/110337784/209471421-e659c50f-639b-454b-b474-748c1614d9b4.png)

**Comment by WillyJL** [comment]
I was looking around your FZ graphics repo and saw this mentioned. I took the liberty of adding it myself

https://github.com/Next-Flip/Momentum-Apps/commit/fa59ab9a99e37658c7896eaa988796c8b8db4260

feel free to take it @xMasterX :D

**Comment by Kuronons** [comment]
Amazing ! O_oV

**Comment by xMasterX** [comment]
I haven't got email when issue was made since this repo was unwatched for some reason
So it was sitting here for 2 years without me knowing about this existing...

Ill merge @Willy-JL 's commit then
